select MEMBER_ID, MEMBER_NAME, GENDER, 
DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
from MEMBER_PROFILE
where MEMBER_PROFILE.TLNO is not NULL 
    and month(DATE_OF_BIRTH) = 3
    and GENDER ="W"
order by MEMBER_ID

